#!/bin/bash
#SBATCH -D /mnt/shared/scratch/hhocking/
#SBATCH --job-name=fasttree_gamma
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=medium
#SBATCH --mem=128G

source /mnt/apps/users/hhocking/conda/bin/activate /mnt/apps/users/hhocking/conda/envs/fasttree

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

mkdir -p /mnt/shared/scratch/hhocking/fasttree_gamma

FastTreeMP -nt -gtr -gamma \
/mnt/shared/scratch/hhocking/panaroo_resultsL/core_gene_alignment_filtered.aln \
> /mnt/shared/scratch/hhocking/fasttree_gamma/core_tree_gamma.newick
